import type { Listing } from "./types";

// Demo inventory — renders the full site before the live Supabase DB is wired,
// and seeds the database (see supabase-schema.sql). Swap for real listings via /admin.
const rwf = (n: number) => `RWF ${n.toLocaleString("en-US")}`;
const rwfMo = (n: number) => `RWF ${n.toLocaleString("en-US")} / month`;

export const SEED_LISTINGS: Listing[] = [
  // ── Properties for sale ──
  {
    id: "p1", slug: "modern-4-bed-villa-kiyovu-kigali", vertical: "property", listing_type: "sale",
    title: "Modern 4-Bedroom Villa in Kiyovu", price: 280000000, price_label: rwf(280000000),
    currency: "RWF", location: "Kiyovu", district: "Nyarugenge",
    description: "A contemporary villa in the heart of Kiyovu — floor-to-ceiling glass, a landscaped garden, rooftop terrace with city views, and a self-contained guest wing. Built and finished to international standard.",
    features: ["Swimming Pool", "Rooftop Terrace", "2-Car Garage", "Garden", "24/7 Security", "Standby Generator", "Solar Water Heating"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80", "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=1200&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80"],
    status: "available", featured: true, created_at: "2026-06-10T09:00:00Z",
    bedrooms: 4, bathrooms: 3, area_sqm: 340, furnished: false,
  },
  {
    id: "p2", slug: "executive-family-home-nyarutarama", vertical: "property", listing_type: "sale",
    title: "Executive Family Home — Nyarutarama", price: 195000000, price_label: rwf(195000000),
    currency: "RWF", location: "Nyarutarama", district: "Gasabo",
    description: "Spacious five-bedroom home on a quiet street near the golf course. Mature garden, domestic quarters, double living areas, and a large covered veranda for entertaining.",
    features: ["Large Compound", "Domestic Quarters", "Borehole", "Covered Veranda", "Perimeter Wall", "Gate House"],
    images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80", "https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=1200&q=80"],
    status: "available", featured: true, created_at: "2026-06-08T09:00:00Z",
    bedrooms: 5, bathrooms: 4, area_sqm: 410, furnished: false,
  },
  {
    id: "p3", slug: "3-bed-bungalow-kibagabaga", vertical: "property", listing_type: "sale",
    title: "3-Bedroom Bungalow in Kibagabaga", price: 98000000, price_label: rwf(98000000),
    currency: "RWF", location: "Kibagabaga", district: "Gasabo",
    description: "Well-built bungalow in a growing Kibagabaga neighbourhood — close to schools and the main road. Solid finishes, a tidy compound, and room to extend.",
    features: ["Parking", "Garden", "Perimeter Wall", "Borehole", "Tiled Floors"],
    images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80", "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1200&q=80"],
    status: "available", featured: false, created_at: "2026-06-05T09:00:00Z",
    bedrooms: 3, bathrooms: 2, area_sqm: 220, furnished: false,
  },
  {
    id: "p4", slug: "luxury-apartment-cbd-kigali", vertical: "property", listing_type: "sale",
    title: "Luxury 2-Bed Apartment — CBD", price: 145000000, price_label: rwf(145000000),
    currency: "RWF", location: "Central Business District", district: "Nyarugenge",
    description: "High-floor apartment in a secure CBD tower with lift, gym, and underground parking. Walk to the Convention Centre, banks, and the best restaurants in town.",
    features: ["Lift", "Gym", "Underground Parking", "24/7 Security", "Fibre Internet", "Balcony"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80"],
    status: "available", featured: false, created_at: "2026-06-02T09:00:00Z",
    bedrooms: 2, bathrooms: 2, area_sqm: 130, furnished: true,
  },

  // ── Houses for rent ──
  {
    id: "r1", slug: "furnished-3-bed-apartment-kimihurura-rent", vertical: "rental", listing_type: "rent",
    title: "Furnished 3-Bed Apartment — Kimihurura", price: 1200000, price_label: rwfMo(1200000),
    currency: "RWF", location: "Kimihurura", district: "Gasabo",
    description: "Fully furnished executive apartment in Kimihurura's most sought-after complex. Concierge, pool, gym, and dedicated parking. Walking distance to embassies and fine dining.",
    features: ["Furnished", "Concierge", "Swimming Pool", "Gym", "Underground Parking", "Fibre Internet", "24/7 Security"],
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80"],
    status: "available", featured: true, created_at: "2026-06-11T09:00:00Z",
    bedrooms: 3, bathrooms: 2, area_sqm: 180, furnished: true,
  },
  {
    id: "r2", slug: "2-bed-house-gisozi-rent", vertical: "rental", listing_type: "rent",
    title: "2-Bedroom House in Gisozi", price: 450000, price_label: rwfMo(450000),
    currency: "RWF", location: "Gisozi", district: "Gasabo",
    description: "Comfortable family house with a private compound in a quiet Gisozi street. Close to international schools and the main road — ideal for a small family.",
    features: ["Private Compound", "Parking", "Garden", "Water Tank", "Perimeter Wall"],
    images: ["https://images.unsplash.com/photo-1592595896551-12b371d546d5?w=1200&q=80"],
    status: "available", featured: false, created_at: "2026-06-07T09:00:00Z",
    bedrooms: 2, bathrooms: 1, area_sqm: 140, furnished: false,
  },
  {
    id: "r3", slug: "studio-apartment-remera-rent", vertical: "rental", listing_type: "rent",
    title: "Furnished Studio — Remera", price: 320000, price_label: rwfMo(320000),
    currency: "RWF", location: "Remera", district: "Gasabo",
    description: "Compact, fully furnished studio in a secure Remera complex. All utilities included. Perfect for a young professional — walk to work and the bus lines.",
    features: ["Furnished", "All Utilities Included", "Fibre Internet", "24/7 Security", "Rooftop Access"],
    images: ["https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&q=80"],
    status: "available", featured: false, created_at: "2026-06-04T09:00:00Z",
    bedrooms: 1, bathrooms: 1, area_sqm: 48, furnished: true,
  },

  // ── Land & plots ──
  {
    id: "l1", slug: "600sqm-titled-plot-nyarutarama", vertical: "land", listing_type: "sale",
    title: "600sqm Titled Plot — Nyarutarama", price: 85000000, price_label: rwf(85000000),
    currency: "RWF", location: "Nyarutarama", district: "Gasabo",
    description: "Flat, titled 600sqm plot in prestigious Nyarutarama. All utilities connected, tarmac access, and a clear title for fast transfer. Ideal for a luxury residential build.",
    features: ["Titled", "All Utilities Connected", "Flat Terrain", "Tarmac Road Access", "Corner Plot", "Close to Golf Course"],
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80"],
    status: "available", featured: true, created_at: "2026-06-09T09:00:00Z",
    area_sqm: 600, zoning: "Residential", title_status: "Freehold Title",
  },
  {
    id: "l2", slug: "1200sqm-commercial-plot-kicukiro", vertical: "land", listing_type: "sale",
    title: "1,200sqm Commercial Plot — Kicukiro", price: 130000000, price_label: rwf(130000000),
    currency: "RWF", location: "Kicukiro", district: "Kicukiro",
    description: "Prime commercial plot on a busy Kicukiro road — high visibility and footfall. Zoned for commercial development with a clean, transferable title.",
    features: ["Titled", "Commercial Zoning", "Main Road Frontage", "High Footfall", "Utilities at Boundary"],
    images: ["https://images.unsplash.com/photo-1542889601-399c4f3a8402?w=1200&q=80"],
    status: "available", featured: false, created_at: "2026-06-03T09:00:00Z",
    area_sqm: 1200, zoning: "Commercial", title_status: "Freehold Title",
  },
  {
    id: "l3", slug: "2500sqm-farm-plot-rebero", vertical: "land", listing_type: "sale",
    title: "2,500sqm Plot with Views — Rebero", price: 60000000, price_label: rwf(60000000),
    currency: "RWF", location: "Rebero", district: "Kicukiro",
    description: "Generous hillside plot with sweeping valley views. Titled and ready for a private estate or a small development. Quiet, green, and only minutes from the city.",
    features: ["Titled", "Valley Views", "Quiet Area", "Access Road", "Room for Estate"],
    images: ["https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=1200&q=80"],
    status: "available", featured: false, created_at: "2026-05-30T09:00:00Z",
    area_sqm: 2500, zoning: "Residential", title_status: "Freehold Title",
  },

  // ── Cars for sale ──
  {
    id: "c1", slug: "toyota-rav4-2019-kigali", vertical: "car", listing_type: "sale",
    title: "Toyota RAV4 2019 — Inspected", price: 28500000, price_label: rwf(28500000),
    currency: "RWF", location: "Kigali", district: "Gasabo",
    description: "Clean, locally-inspected RAV4 with full service history. One owner, accident-free, new tyres. Drives like new — ready for Rwandan roads.",
    features: ["Full Service History", "Accident-Free", "New Tyres", "Reverse Camera", "Alloy Wheels", "Bluetooth"],
    images: ["https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=1200&q=80", "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80"],
    status: "available", featured: true, created_at: "2026-06-12T09:00:00Z",
    make: "Toyota", model: "RAV4", year: 2019, mileage_km: 62000, transmission: "Automatic", fuel_type: "Petrol", condition: "Used", body_type: "SUV",
  },
  {
    id: "c2", slug: "mercedes-benz-c200-2017", vertical: "car", listing_type: "sale",
    title: "Mercedes-Benz C200 2017", price: 32000000, price_label: rwf(32000000),
    currency: "RWF", location: "Kigali", district: "Nyarugenge",
    description: "Elegant C-Class in excellent condition. Leather interior, premium sound, and a smooth, economical engine. Serviced at the dealer — papers in order.",
    features: ["Leather Interior", "Premium Sound", "Dealer Serviced", "Sunroof", "Parking Sensors"],
    images: ["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=80", "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=1200&q=80"],
    status: "available", featured: true, created_at: "2026-06-10T09:00:00Z",
    make: "Mercedes-Benz", model: "C200", year: 2017, mileage_km: 78000, transmission: "Automatic", fuel_type: "Petrol", condition: "Used", body_type: "Sedan",
  },
  {
    id: "c3", slug: "toyota-land-cruiser-prado-2016", vertical: "car", listing_type: "sale",
    title: "Toyota Land Cruiser Prado 2016", price: 45000000, price_label: rwf(45000000),
    currency: "RWF", location: "Kigali", district: "Gasabo",
    description: "Powerful, reliable Prado built for any terrain. 7 seats, strong diesel engine, and a body in great shape. The go-anywhere family and business vehicle.",
    features: ["7 Seats", "4WD", "Diesel", "Tow Bar", "Roof Rails", "Leather Seats"],
    images: ["https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=80"],
    status: "available", featured: false, created_at: "2026-06-06T09:00:00Z",
    make: "Toyota", model: "Land Cruiser Prado", year: 2016, mileage_km: 110000, transmission: "Automatic", fuel_type: "Diesel", condition: "Used", body_type: "SUV",
  },
  {
    id: "c4", slug: "suzuki-swift-2020", vertical: "car", listing_type: "sale",
    title: "Suzuki Swift 2020 — Low Mileage", price: 14500000, price_label: rwf(14500000),
    currency: "RWF", location: "Kigali", district: "Kicukiro",
    description: "Economical, nimble Swift — perfect first car or city runabout. Very low mileage, fuel-sipping engine, and easy parking. Excellent condition throughout.",
    features: ["Low Mileage", "Fuel Efficient", "Bluetooth", "Reverse Camera", "Single Owner"],
    images: ["https://images.unsplash.com/photo-1549924231-f129b911e442?w=1200&q=80"],
    status: "available", featured: false, created_at: "2026-06-01T09:00:00Z",
    make: "Suzuki", model: "Swift", year: 2020, mileage_km: 34000, transmission: "Automatic", fuel_type: "Petrol", condition: "Used", body_type: "Hatchback",
  },
];
